name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  call-clabot-workflow:
    uses: Roblox/cla-signature-bot/.github/workflows/clabot-workflow.yml@master
    with:
      whitelist: "sfong-roblox,NickChoiRBX,JanBerktold,Ali2Arslan,kushudai"
      use-remote-repo: true
      remote-repo-name: "roblox/cla-bot-store"
    secrets: inherit
