name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        features: ["", "--no-default-features --features rustls-native"]
    runs-on: "ubuntu-latest"
    container: rust:1.61.0

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build ${{ matrix.features }}

  test:
    strategy:
      matrix:
        features: ["", "--no-default-features --features rustls-native"]
    runs-on: "ubuntu-latest"
    container: rust:1.61.0
    services:
      consul:
        image: consul:1.9.3
        options: >-
          -log-level=debug
          -e HELLO=1
    env:
      CONSUL_HTTP_ADDR: http://consul:8500

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: cargo test ${{ matrix.features }}
